dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=contest-cities-game

matrix:
  include:
    # Android
    - env: TARGET=aarch64-linux-android DISABLE_TESTS=1

    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "oX3IVGm9K/I6I0NBVTsqi4l7FFzw7v9KxYsUVBMs6R/vD8VFs52DvN+Zhb+TFL8fpNUOT5rKsRL8G48VMzevDWLy7UolqFlJ+MbV/yPuOEPy7xSEECWeRm56YQbBkvcyH9Cze100g3gSfDt0y0RySjmuve7Z+qlZ7VRmq58JdDjzxSJz0pK6pEwlBY25ZhbxyN0TX7sTOGhx1h0g4qEEHnYQ0VGoFTrjGUsuYMEKoBunlP46st9wFXP3fTAuIbN1LYU+93GgRLCvrwasiIUpN9dXw4eE8/WLc7Shan2KU5rAsGcfTSYCUWp+XM0oIRnK7SuDA2zowMaU+1RZdWcIgBWXj250n7s4+fa+u3P+3YGrUlCT+76Fo8Sq2V86xzDbPlwsbkxjvTntY+mlHLSEncjScgaDyOfAiF78YyHMb4W74tkgsSWFkfWPnc/o63TUQywKvaqbXnqSbhQnI7SAs8q4rCX5k9dYuuSN9bsv8S0288drALSpCS3eToLBNorgJm8ZMJwr3OIp3A10E1Zd2rj5V4HBu7hib/oPXZ5CJFVR7WfX7UuMtQy5+ytXs9seoqP143Uaf1DVsrjqDA2R14hDAcyYWJccPJrzC1wlCqCWCLPtNlyDQlSG0OK5/Ti1+ZpZAfVn20Zjg+7wt2M5vbl5LY26hk4df6HBSvu3eck="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
