[package]
name = "contest-cities-game"
version = "0.1.0"
authors = ["dantistnfs <dantistnfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph="*"
